### ISSUE TITLE
Does this plugin work with 1.7.1?

### ISSUE THREAD

**Issue by FlexFM** [YOURLS/google-safe-browsing#2]
Hi

I just did a fresh install and 'Plugin Google Safe Browsing is not configured' so went to Manage Plugins > Google Safe Browsing and I get Fatal error: Call to undefined function ozh_yourls_gsb_display_page() in /home/username/public_html/user/plugins/google-safe-browsing/plugin.php on line 102

this is a fresh 1.7.1 install

thanks

**Comment by master3395** [comment]
I get the same error.

**Comment by KenSharp** [comment]
In 1.7.2, the server keeps complaining that the API key is not authorised. It is, and it works. The dev console confirms that the script is making no attempt to contact the GSB servers at all. It doesn't work.

**Comment by Zitt** [comment]
I think I found a fix.

First; you must enable the legacy Safe Browsing Lookup API (v3) ... not >= V4. V4 only seems to support the post method... where the yourls implementation relys on GET method.

Open google-safe-browsing/includes/class-gsb.php
got to end of file near line 71.
locate :

`    private function request() {
        $api_url = sprintf( 'https://sb-ssl.google.com/safebrowsing/api/lookup?client=%s&**api**key=%s&appver=%s&pver=%s&url=%s',
            self::CLIENT,
            $this->api_key,
            self::APP_VER,
            self::PROTOCOL_VER,
            $this->url
        );
`
remove **api**. setting the variable to only key=%s  since the v3 api doesn't understand apikey... only key.

Final code will look like this:
`        $api_url = sprintf( 'https://sb-ssl.google.com/safebrowsing/api/lookup?client=%s&key=%s&appver=%s&pver=%s&url=%s',
            self::CLIENT,
            $this->api_key,
            self::APP_VER,
            self::PROTOCOL_VER,
            $this->url
        ); `

**Comment by master3395** [comment]
@Zitt Could you pull a update request?
also idk if this is related to this pull request.
https://github.com/YOURLS/google-safe-browsing/pull/3

**Comment by LeoColomb** [comment]
@ozh Can be closed as fixed by #3
